// Creates a new Prisma migration from the difference between the live
// database (DIRECT_URL) and prisma/schema.prisma.
//
//   npm run db:new -- add_meal_notes
//
// Supabase's auth schema/extensions make Prisma's shadow-database flow
// (`prisma migrate dev`) impractical, so we diff against the real DB instead.
// Always review the generated SQL before running `npm run db:deploy`.
import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const raw = process.argv.slice(2).join("_");
const name = raw.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
if (!name) {
  console.error("Usage: npm run db:new -- <migration_name>");
  process.exit(1);
}

// Arguments are fixed strings (no user input), so a single shell command is safe.
const prisma = (args) =>
  spawnSync(`npx prisma ${args.join(" ")}`, { shell: true, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });

// The diff is taken against the live DB, so every existing migration must be applied first.
const status = prisma(["migrate", "status"]);
if (status.status !== 0) {
  console.error(status.stdout + status.stderr);
  console.error("\n✖ Database has unapplied migrations or can't be reached. Run `npm run db:deploy` first.");
  process.exit(1);
}

const diff = prisma([
  "migrate",
  "diff",
  "--from-config-datasource",
  "--to-schema",
  "prisma/schema.prisma",
  "--script",
  "--exit-code",
]);
if (diff.status === 0) {
  console.log("✓ schema.prisma already matches the database — nothing to migrate.");
  process.exit(0);
}
if (diff.status !== 2) {
  console.error(diff.stdout + diff.stderr);
  process.exit(1);
}

const d = new Date();
const pad = (n) => String(n).padStart(2, "0");
const stamp = `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}`;
const dir = path.join("prisma", "migrations", `${stamp}_${name}`);
mkdirSync(dir, { recursive: true });
const header =
  "-- Generated by `npm run db:new` from schema.prisma.\n" +
  "-- Review before deploying. For new tables add RLS + policies by hand, e.g.:\n" +
  "--   ALTER TABLE public.<table> ENABLE ROW LEVEL SECURITY;\n" +
  "--   CREATE POLICY \"<table>: self\" ON public.<table> FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());\n\n";
writeFileSync(path.join(dir, "migration.sql"), header + diff.stdout.trim() + "\n");
console.log(`✓ Created ${dir}/migration.sql\n\n${diff.stdout.trim()}\n\nNext: review it, then run \`npm run db:deploy\`.`);
